### ISSUE TITLE
fix: align Endpoint repository-read confinement with canonical GitHub path encoding

### ISSUE THREAD

**Issue by yohnark** [yohn-jp/gh-inari#981]
### Problem

#958 has now failed three times at the same production authority boundary: the hosted human repository-read confinement introduced by #954 does not implement the complete bounded GET surface actually consumed by #955.

The failures were sequential only because the validator was patched one request shape at a time:

1. valid percent-encoded branch refs such as `git/ref/heads/feat%2F...` were rejected;
2. after #982, valid tree reads such as `git/trees/<ref>?recursive=1` were rejected;
3. after #984, the next canonical Change evidence read `pulls?...state=all&head=...&base=...&per_page=100` was rejected.

This source Issue is therefore redefined around the actual composed production contract, not individual query strings. #958 remains certification-only and must not discover another request shape that the #954 boundary should already have admitted.

### Capability

Converge the #954 request-scoped GET-only repository transport with the complete, bounded GitHub read surface reachable from one real #955 rooted `work.read`.

The transport remains repository-confined and fail-closed. It must admit only structurally valid requests belonging to the known production read surface below; it must not become a generic GitHub proxy.

### Canonical rooted-work read surface

The authority is the current #840 Epic code path:

`HostedEndpointWorkReader`
→ `createGitHubImplementationFrontierRepository`
→ `GitHubAdapter` / `GitHubIssueRelationObservationAdapter`
→ `GitHubChangeStateProjector`
→ `GitHubRepositoryEvidenceReader`
→ Operational/Semantic observations.

A complete rooted `work.read` may issue these repository-scoped GET targets:

#### Repository / Issue / refs

- `repos/<owner>/<repo>`
- `repos/<owner>/<repo>/issues/<issue>`
- `repos/<owner>/<repo>/git/ref/heads/<encoded-ref>`
- `repos/<owner>/<repo>/git/matching-refs/heads/`
- `repos/<owner>/<repo>/git/trees/<encoded-ref>?recursive=1`
- `repos/<owner>/<repo>/git/blobs/<encoded-sha>`

#### Native Issue relation closure

- `repos/<owner>/<repo>/issues/<issue>/dependencies/blocked_by?per_page=100&page=<1..10>`

#### Canonical Change PR discovery

- `repos/<owner>/<repo>/pulls?state=all&head=<encoded-owner:branch>&base=<encoded-base>&per_page=100`
- `repos/<owner>/<repo>/pulls/<pr>`

#### Operational Issue / PR evidence

The operational collection reader uses bounded pages of 100, maximum 10 pages:

- `issues/<issue>/comments?per_page=100&page=<1..10>`
- `pulls/<pr>/comments?per_page=100&page=<1..10>`
- `pulls/<pr>/reviews?per_page=100&page=<1..10>`
- `pulls/<pr>/files?per_page=100&page=<1..10>`
- `commits/<sha>/check-runs?per_page=100&page=<1..10>`
- `commits/<sha>/status?per_page=100&page=<1..10>`
- `branches/<encoded-base>/protection/required_status_checks`

The review-decision GraphQL read is intentionally unavailable through the #954 repository-read capability because the exposed capability has no GraphQL method; existing Operational Observation already represents that evidence as unavailable.

No mutation request belongs to this surface.

### Contract

Implement request admission as a path-family + query-schema contract, not as a growing string allowlist.

- Prove hostname and exact raw repository root before interpreting any repository-relative path or query.
- Parse the raw target without URL normalization that could rewrite encoded separators.
- Match only the repository-relative path families listed above.
- Validate dynamic segments by their semantic type: positive decimal Issue/PR/page values, bounded SHA/ref/provider text, and syntactically complete percent encoding.
- Query keys are route-specific. Unknown keys, duplicate keys, missing required keys, invalid values, extra structural `?`, fragments, malformed escapes, controls, backslashes and authority/absolute-URL forms fail before provider I/O.
- Query parameter order must not be authority. Parse the query structurally and compare the exact key set and bounded values for that route.
- For canonical PR discovery, decode query values only for validation; require `state=all`, `per_page=100`, one `head`, one `base`, and ensure decoded `head` is rooted in the authenticated repository owner namespace. Do not reconstruct a different provider target.
- For bounded pagination, require `per_page=100` and integer `page` in `1..10`.
- For governance tree reads, require exactly `recursive=1`.
- Routes with no query must reject any query.
- The original validated raw target is sent unchanged to GitHub.
- The capability stays GET-only, request-scoped, host-bound and credential-opaque.
- Repository ID authorization and App-user authentication remain unchanged.

### Required proof

Do not test the validator only with hand-authored strings.

Add a focused production-surface conformance test that obtains the real #954 repository-read capability and then drives the actual emitters used by #955 across all query-bearing families:

- actual `GitHubAdapter.findBranch()`;
- actual `GitHubAdapter.getRepositoryTree()`;
- actual `GitHubIssueRelationObservationAdapter.observeBlockedBy()`;
- actual `GitHubRepositoryEvidenceReader.readPullRequests()`;
- actual `GitHubAdapter.observeIssue()`;
- actual `GitHubAdapter.observePullRequest()`.

The fixture may return bounded deterministic GitHub responses, but request targets must be emitted by production modules. The test must record every provider request and prove all expected request families cross the #954 boundary without an authorization rejection.

Also retain explicit negative tests for malformed encoding, traversal, cross-repository access, unknown query keys, duplicate query keys, out-of-range pagination, wrong hostname and non-GET behavior.

### Acceptance criteria

- [ ] The complete request matrix above is represented by one explicit, reviewable admission contract.
- [ ] Every query-bearing request family used by current #955 rooted `work.read` is generated by its real production emitter and accepted by #954.
- [ ] No current #955 rooted-work GET request depends on a query/path form absent from the admission contract.
- [ ] Unknown repository-relative path families fail before provider I/O.
- [ ] Unknown, duplicate or route-inappropriate query keys fail before provider I/O.
- [ ] Pagination is bounded to `per_page=100`, `page=1..10`.
- [ ] PR discovery is bounded to the current canonical `state=all`, `head`, `base`, `per_page=100` schema.
- [ ] Tree reads are bounded to `recursive=1`.
- [ ] Raw/encoded traversal, controls, malformed escapes, fragments, absolute/authority forms and cross-repository roots fail closed.
- [ ] GET-only, hostname binding, immutable repository identity and credential secrecy remain unchanged.
- [ ] Existing #982 and #984 compatibility tests remain green.
- [ ] Focused tests include an actual-emitter surface-conformance test rather than only isolated validator examples.
- [ ] Full `pnpm run verify` is green.
- [ ] After the corrective Implementation lands, #958 is rerun exactly once from the new Epic head. Any later blocker must be a different product contract, not another missing GET path/query family from this matrix.

### Non-goals

Changing GitHubAdapter or RepositoryEvidenceReader request generation; adding mutation access; exposing GraphQL; making the human transport a generic GitHub proxy; changing Endpoint capabilities/work projection; patching #958 certification.

### Constraints

#982 and #984 are partial historical fixes under this source Issue. They are not sufficient acceptance evidence for #981 by themselves.

The next Implementation must audit and cover the complete production surface above before #958 is resumed.
